#
# default_config.yaml
#

hyperparameters:
  batch_size: 16     # number of sequences to train on in parallel
  block_size: 8      # max context length for predictions
  max_iters: 3000
  lr: 1e-2           # learning rate
  wd: 1e-3           # weight decay
  eval_iters: 50
  eval_interval: 200
  num_embeddings: 32
  key_variations: 4
  vocab_size: 3225   # (128 MIDI notes + 1 rest token) * 25 possible durations